# -*- coding: utf-8 -*-
"""문자열_92890_문자열반복.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Vvfr4STb9_llVQVkQiCoz2FBNch4cK0
"""

n = int(input())

for _ in range(n):
    cnt, word = input().split()
    for x in word:
        print(x*int(cnt), end='')  # end='' 옆으로 붙임
    print()  # 줄넘김