# -*- coding: utf-8 -*-
"""문자열_10809_알파벳찾기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Vvfr4STb9_llVQVkQiCoz2FBNch4cK0
"""

word = input()
alphabet = list(range(97,123))  # 아스키코드 숫자 범위

for x in alphabet :
    print(word.find(chr(x)))